"""followers

Revision ID: 07f9c35ce4b6
Revises: 35b046b0d710
Create Date: 2019-02-22 16:04:43.251953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f9c35ce4b6'
down_revision = '35b046b0d710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_unique_constraint(None, 'user', ['facebook'])
    op.create_unique_constraint(None, 'user', ['skype'])
    op.create_unique_constraint(None, 'user', ['telegram'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('followers')
    # ### end Alembic commands ###
