"""new fields in user model

Revision ID: 35b046b0d710
Revises: 03bc354f1929
Create Date: 2019-02-15 12:52:46.007812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b046b0d710'
down_revision = '03bc354f1929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('facebook', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('skype', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('telegram', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'user', ['skype'])
    op.create_unique_constraint(None, 'user', ['telegram'])
    op.create_unique_constraint(None, 'user', ['facebook'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'telegram')
    op.drop_column('user', 'skype')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'facebook')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
